logging:
  level:
    com.kaituo.comparison.back: debug
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1002

spring:
  aop:
    proxy-target-class: true
    auto: true

soul:
  sync:
    strategy: websocket
    websocket:
      url: ws://localhost:1001/websocket